"""Market-data job types, statuses, and feature defaults."""

from __future__ import annotations

JOB_SYNC_EXCHANGES = "SYNC_EXCHANGES"
JOB_SYNC_INSTRUMENTS = "SYNC_INSTRUMENTS"
JOB_DAILY_EOD = "DAILY_EOD"
JOB_CORRECTION = "CORRECTION"
JOB_RECONCILE = "RECONCILE"

ALL_JOB_TYPES = {
    JOB_SYNC_EXCHANGES,
    JOB_SYNC_INSTRUMENTS,
    JOB_DAILY_EOD,
    JOB_CORRECTION,
    JOB_RECONCILE,
}

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_DEAD = "dead"

DATA_STATUS_FINAL = "FINAL"

INGEST_STATUS_QUEUED = "QUEUED"
INGEST_STATUS_RUNNING = "RUNNING"
INGEST_STATUS_DOWNLOADED = "DOWNLOADED"
INGEST_STATUS_NORMALIZED = "NORMALIZED"
INGEST_STATUS_VALIDATED = "VALIDATED"
INGEST_STATUS_PUBLISHED = "PUBLISHED"
INGEST_STATUS_FAILED = "FAILED"
INGEST_STATUS_PARTIALLY_FAILED = "PARTIALLY_FAILED"

PROVIDER_FAKE = "fake"
PROVIDER_LIVE = "live"

BACKOFF_BASE_SECONDS = 30
DEFAULT_MAX_ATTEMPTS = 5
